### ISSUE TITLE
travis integration for lint checks

### ISSUE THREAD

**Issue by rahgurung** [sofiabsilva/radio-chrome-extension#2]
How about adding lint checks using travis integration, can I do that for you?

**Comment by sofiabsilva** [comment]
@gurungrahul2 sure! I have no experience with that yet.

**Comment by rahgurung** [comment]
@sofiabsilva Follow the first three step of https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci and leave the rest to me, I am also new at learning CI, but we can do it.

**Comment by sofiabsilva** [comment]
Thanks @gurungrahul2 I need to learn more about this.

**Comment by rahgurung** [comment]
@sofiabsilva https://www.youtube.com/watch?v=alMRNeRJKUE
